spring:
  application:
    name: mvc

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: true

app:
  cache:
    cache-names:
      - booksByCategory
      - searchBook
      - bookById

    caches:
      booksByCategory:
        expiry: 24h
      searchBook:
        expiry: 24h
      bookById:
        expiry: 24h
